spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/springcrud
    driver-class-name: org.postgresql.Driver
    username: userok
    password: p@ssw0rd
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true

