create table phrases (
    id int8 generated by default as identity,
    eng_phrase varchar(255) not null,
    form varchar(50),
    rus_phrase varchar(255) not null,
    tense varchar(50),
    user_id int8, primary key (id)
);

create table user_role (
    user_id int8 not null,
    roles varchar(255)
);

create table users (
    id int8 generated by default as identity,
    active boolean,
    date_of_create timestamp,
    email varchar(255) not null,
    name varchar(255) not null,
    password varchar(1000) not null,
    phone_number varchar(255),
    primary key (id)
);

alter table if exists phrases
    add constraint phrases_user_fk
    foreign key (user_id) references users;

alter table if exists user_role
    add constraint user_role_user_fk
    foreign key (user_id) references users;