insert into phrases (eng_phrase, form, rus_phrase, tense, user_id)
values ('Mary ate ice-cream yesterday', 'affirmativeCreate', 'Мэри вчера ела мороженое', 'pastSimple', 1),
       ('Who ate ice-cream yesterday?', 'questionsCreate', 'Кто вчера ел мороженое?', 'pastSimple', 1),
       ('Mark did not come yesterday', 'negativeCreate', 'Марк не пришел вчера', 'pastSimple', 1),
       ('I go to work every day', 'affirmativeCreate', 'Я хожу на работу каждый день', 'presentSimple', 1),
       ('Do they play football?', 'questionsCreate', 'Они играют в футбол?', 'presentSimple', 1),
       ('She does not like the weather in London', 'negativeCreate', 'Ей не нравится погода в Лондоне', 'presentSimple', 1),
       ('I will read an interesting book', 'affirmativeCreate', 'Я буду читать интересную книгу', 'futureSimple', 1),
       ('Will you buy that blue car?', 'questionsCreate', 'Ты купишь ту синюю машину?', 'futureSimple', 1),
       ('We will not find the hotel tomorrow', 'negativeCreate', 'Мы не найдем отель завтра', 'futureSimple', 1),
       ('She was painting a new picture', 'affirmativeCreate', 'Она рисовала новую картину', 'pastContinuous', 1),
       ('Were we driving the main road?', 'questionsCreate', 'Мы ехали по главной дороге?', 'pastContinuous', 1),
       ('I was not drinking coffee', 'negativeCreate', 'Я не пил кофе', 'pastContinuous', 1),
       ('We are moving into a new house', 'affirmativeCreate', 'Мы переезжаем в новый дом', 'presentContinuous', 1),
       ('Are they swimming?', 'questionsCreate', 'Они плавают?', 'presentContinuous', 1),
       ('She is not dancing', 'negativeCreate', 'Она не танцует', 'presentContinuous', 1),
       ('It will be working', 'affirmativeCreate', 'Оно будет работать', 'futureContinuous', 1),
       ('Will we be walking?', 'questionsCreate', 'Мы будем гулять?', 'futureContinuous', 1),
       ('They will not be fighting', 'negativeCreate', 'Они не будут драться', 'futureContinuous', 1),
       ('He had washed the dirty plates', 'affirmativeCreate', 'Он вымыл грязные тарелки', 'pastPerfect', 1),
       ('Had he passed his exam?', 'questionsCreate', 'Он сдал свой экзамен?', 'pastPerfect', 1),
       ('She had not washed her clothes', 'negativeCreate', 'Она не постирала свою одежду', 'pastPerfect', 1),
       ('I’ve done my tasks', 'affirmativeCreate', 'Я выполнил свои задачи', 'presentPerfect', 1),
       ('Has she just arrived home?', 'questionsCreate', 'Она только что приехала домой?', 'presentPerfect', 1),
       ('It has not turned on', 'negativeCreate', 'Оно не включилось', 'presentPerfect', 1),
       ('We will have decided by tomorrow morning', 'affirmativeCreate', 'Мы решим к завтрашнему утру', 'futurePerfect', 1),
       ('Will I have done this project by 9 o’clock tomorrow?', 'questionsCreate', 'Я закончу этот проект завтра к девяти часам?', 'futurePerfect', 1),
       ('He will not have finished his work when I call him', 'negativeCreate', 'Он не закончит свою работу, когда я ему позвоню', 'futurePerfect', 1),
       ('I had been working for a long time', 'affirmativeCreate', 'Я работал в течение долгого времени', 'pastPerfectCont', 1),
       ('Had he been looking through the window?', 'questionsCreate', 'Он смотрел в окно?', 'pastPerfectCont', 1),
       ('I had not been working for a long time', 'negativeCreate', 'Я не работал в течение долгого времени', 'pastPerfectCont', 1),
       ('They have been travelling', 'affirmativeCreate', 'Они путешествовали', 'presentPerfectCont', 1),
       ('Have I been dancing?', 'questionsCreate', 'Я танцевал?', 'presentPerfectCont', 1),
       ('We have not been listening', 'negativeCreate', 'Мы не слушали', 'presentPerfectCont', 1),
       ('She will have been reading', 'affirmativeCreate', 'Она будет читать', 'futurePerfectCont', 1),
       ('Will it have been falling?', 'questionsCreate', 'Оно будет падать?', 'futurePerfectCont', 1),
       ('We will not have been playing', 'negativeCreate', 'Мы не будем играть', 'futurePerfectCont', 1)
;
