package com.english.springcrud.models.enums;

public enum Tense {
    PAST_SIMPLE,
    PRESENT_SIMPLE,
    FUTURE_SIMPLE,

    PAST_CONTINUOUS,
    PRESENT_CONTINUOUS,
    FUTURE_CONTINUOUS,

    PAST_PERFECT,
    PRESENT_PERFECT,
    FUTURE_PERFECT,

    PAST_PERFECT_CONT,
    PRESENT_PERFECT_CONT,
    FUTURE_PERFECT_CONT
}
